import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import "./globals.css";
import { cn, setAuth } from "@/lib/utils";
import { Toaster } from "@/components/ui/toaster";
import StoreProvider from "./StoreProvider";
import Header from "@/components/Header";
import { Button } from "@/components/ui/button";
import axios from "axios";
import { ReloadIcon } from "@radix-ui/react-icons";
import { useEffect, useState } from "react";
import { useToast } from "@/components/ui/use-toast";

import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { updateUserInfo } from "@/lib/store/features/user";
import LoginSignupDialog from "@/components/LoginSignupDialog";
const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

const LoadingButton = () => {
  return (
    <Button disabled>
      <ReloadIcon className="mr-2 h-4 w-4 animate-spin" />
      Please wait
    </Button>
  );
};
const getFormData = () => {
  const email = (document.querySelector("#email") as any).value.trim();
  const password = (document.querySelector("#password") as any).value.trim();
  return { email, password };
};
export const metadata: Metadata = {
  title: "你的youtube资源package",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        <StoreProvider>
          
          <LoginSignupDialog />
          {children}
        </StoreProvider>
        <Toaster />
      </body>
    </html>
  );
}
